### ISSUE TITLE
开发插件时，框架无法实现最简单的视图功能

### ISSUE THREAD

**Issue by peinhu** [walkor/webman-framework#51]
Webman-framework v1.3.21
Workerman version:4.0.42          
PHP version:7.4.3

报错内容：
```php
//不知道为什么会有个Admin
ErrorException: include(/vagrant/webman1/app/Admin/view/hello.html): failed to open stream: No such file or directory in /vagrant/webman1/vendor/workerman/webman-framework/src/support/view/Raw.php:60
Stack trace:
#0 /vagrant/webman1/vendor/workerman/webman-framework/src/support/view/Raw.php(60): {closure}()
#1 /vagrant/webman1/vendor/workerman/webman-framework/src/support/view/Raw.php(60): include()
#2 /vagrant/webman1/support/helpers.php(165): support\view\Raw::render()
#3 /vagrant/webman1/vendor/foo/admin/src/TestController.php(7): view()
#4 /vagrant/webman1/vendor/workerman/webman-framework/src/App.php(135): Foo\Admin\TestController->SayHello()
#5 /vagrant/webman1/vendor/workerman/workerman/Connection/TcpConnection.php(638): Webman\App->onMessage()
#6 /vagrant/webman1/vendor/workerman/workerman/Events/Select.php(295): Workerman\Connection\TcpConnection->baseRead()
#7 /vagrant/webman1/vendor/workerman/workerman/Worker.php(2465): Workerman\Events\Select->loop()
#8 /vagrant/webman1/vendor/workerman/workerman/Worker.php(1574): Workerman\Worker->run()
#9 /vagrant/webman1/vendor/workerman/workerman/Worker.php(1416): Workerman\Worker::forkOneWorkerForLinux()
#10 /vagrant/webman1/vendor/workerman/workerman/Worker.php(1390): Workerman\Worker::forkWorkersForLinux()
#11 /vagrant/webman1/vendor/workerman/workerman/Worker.php(557): Workerman\Worker::forkWorkers()
#12 /vagrant/webman1/start.php(112): Workerman\Worker::runAll()
#13 {main}
```

复现流程：

1.创建一个插件 `php webman plugin:create --name=foo/admin`

2.在vendor/foo/admin/src下新建TestController.php文件，内容：
```php
<?php
namespace Foo\Admin;

class TestController{
    function SayHello(){
        return view('hello');
    }
}
```

3.在app\view下新建hello.html，内容：
```php
<html>
<body>
Hello.
</body>
</html>
```

4.在config/route.php中添加：
`Route::get('/hello', [\Foo\Admin\TestController::class, 'SayHello']);`

运行程序，访问/hello，直接报错。
发现报错内容`/vagrant/webman1/app/Admin/view/hello.html`，app和view之间多了个奇怪的Admin，感觉是来自于命名空间？不理解为什么会自动加上这个。

**Comment by walkor** [comment]
Admin应用下会自动使用Admin下的模版

**Comment by peinhu** [comment]
问题这不是多应用，只是路由中用到了插件中的一个TestController类，命名空间是Foo\Admin，但是框架似乎把插件识别成多应用了，识别成了Admin应用，不明白为什么，还是设定本身就是“一个插件相当于一个应用”？

**Comment by walkor** [comment]
目前的插件是基础插件，你这种带视图的属于应用插件，应用插件在1.4版本会支持，1.4版本预计8月15日发布。到时候用1.4吧

**Comment by peinhu** [comment]
好的谢谢，等1.4发布了我再试试把laravel的插件移植过来。
